version: "3.9"
services:
  kabasalt_downloader:
    build:
      context: .

    image: kabasalt_data_downloader
    container_name: kabasalt_data_downloader

    # for interactive mode e.g. for entrypoint /bin/shell
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    entrypoint: "bash download.sh"
    #init: true
    env_file:
      - .env

    volumes:
      - type: volume
        source: data
        target: /home/data

volumes:
  data: