services:
  kabasalt:
    image: kabasalt_data_downloader
    container_name: kabasalt_data_downloader

    # Specifying an init process ensures the usual responsibilities of an init system,
    # such as reaping zombie processes, are performed inside the created container.
    # https://docs.docker.com/engine/reference/run/#specify-an-init-process
    init: true

    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
    ports:
      - 9998:9998
    volumes:
      - type: volume
        source: data
        target: /home/aicrowd/data/

volumes:
  data: