version: "3.9"
services:
  kabasalt_downloader:
    build:
      context: .
    image: kabasalt_data_downloader
    container_name: kabasalt_data_downloader
    entrypoint: "./docker-entrypoint.sh"
    init: true
    tty: true        # docker run -t
    env_file:
      - .env

    volumes:
      - type: volume
        source: data
        target: /home/data

volumes:
  data:
