version: "3.9"
services:
  kabasalt_downloader:
    build:
      context: .
    image: kabasalt_data_downloader
    container_name: kabasalt_data_downloader
    entrypoint: "./docker-entrypoint.sh"
    init: true
    tty: true        # like -t in docker run -t -- enables us to see container output in terminal
    env_file:
      - .env

    volumes:
      - type: volume
        source: data_wombat2
        target: /home/data_wombat
        volume:
          nocopy: true
      - type: volume
        source: data
        target: /home/data

volumes:
  data_wombat2:
    driver_opts:
      type: "nfs"
      o: "addr=ipe-wombat.fzi.de,nolock,soft,rw"
      device: ":/data/share/BASALT2"
  data: